version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dannio:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "dan's test"
workflows:
  node-tests:
    jobs:
      - node/test
      - dannio:
          requires:
            - node/test
