version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dannio:
    steps:
      - checkout
      - run: echo "dan's test"
workflows:
  node-tests:
    jobs:
      - node/test
  dan_test:
    jobs:
      - dannio
